/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.model.BankAccount;
import com.model.BankTransaction;
import edu.sit.cs.db.CSDbDelegate;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author BlueScreen
 */
public class create_account extends javax.swing.JFrame {

    /**
     * Creates new form create_account
     */
    public create_account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idno = new javax.swing.JTextField();
        birthdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deposit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        revenue = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/fullname.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/deposit label.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 100, 80, 30);

        jRadioButton1.setContentAreaFilled(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(530, 150, 60, 30);

        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(610, 150, 40, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/FEMALE.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(630, 150, 0, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/ID NUM.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 100, 30);
        getContentPane().add(idno);
        idno.setBounds(160, 150, 170, 30);
        getContentPane().add(birthdate);
        birthdate.setBounds(530, 200, 110, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/ADDRESS.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 270, 90, 100);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/BIRTH.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 200, 140, 30);
        getContentPane().add(deposit);
        deposit.setBounds(530, 100, 170, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/AGE.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 250, 100, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/EMAIL.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 250, 60, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(160, 100, 170, 30);
        getContentPane().add(email);
        email.setBounds(160, 250, 170, 30);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 300, 166, 96);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/DMY.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 200, 60, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/CARRER.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 300, 80, 30);
        getContentPane().add(revenue);
        revenue.setBounds(530, 350, 170, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select", "Student", "Business", "Owner", "Commerce", "etc." }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(530, 300, 110, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/REVENUE.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 350, 250, 30);
        getContentPane().add(phone);
        phone.setBounds(160, 200, 170, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/PHONE NUM.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-20, 200, 170, 30);
        getContentPane().add(age);
        age.setBounds(530, 250, 170, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/close.png"))); // NOI18N
        jButton3.setToolTipText("Cancel");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 410, 80, 90);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/ok.png"))); // NOI18N
        jButton2.setToolTipText("Next");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 420, 80, 70);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/create account.png"))); // NOI18N
        jLabel14.setToolTipText("Menu");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 20, 680, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/GENDER.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 150, 80, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/MALE.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(540, 150, 0, 30);

        setSize(new java.awt.Dimension(769, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null,
            "Are you sure?",
            "Cancal",
            JOptionPane.YES_NO_OPTION);
        System.out.print(n); // Use n for response
        if(n==1){
            setVisible(true);
        }else{
            displayApp profile = new displayApp();
            profile.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null,
            "Sucess! your account was created",
            "Message",
            JOptionPane.YES_NO_OPTION);
        System.out.print(n);
        if(n == 1){
            setVisible(true);  
        }else{
            String gender = "";
            if(jRadioButton1.isSelected()){
                gender = "M";
            }else if(jRadioButton2.isSelected()){
                gender = "F";
            }
            BankAccount.openAccount(name.getText(), Double.parseDouble(deposit.getText()), gender, email.getText(),
                                    phone.getText(), idno.getText(), revenue.getText(),jComboBox2.getSelectedItem().toString()
                                    ,Integer.parseInt(age.getText()), birthdate.getText(), address.getText());
            
            displayApp profile = new displayApp();
            profile.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField deposit;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idno;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField revenue;
    // End of variables declaration//GEN-END:variables

    

   
}
