/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.model.BankAccount;
import com.model.BankOfficer;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author BlueScreen
 */
public class emp_login extends javax.swing.JFrame {

    /**
     * Creates new form displayApp
     */
    public emp_login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in");
        setResizable(false);
        getContentPane().setLayout(null);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/locked.png"))); // NOI18N
        loginButton.setToolTipText("Enter");
        loginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(80, 170, 70, 70);

        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/password.png"))); // NOI18N
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(20, 100, 130, 20);

        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/username.png"))); // NOI18N
        getContentPane().add(usernameLabel);
        usernameLabel.setBounds(20, 30, 120, 20);
        getContentPane().add(user);
        user.setBounds(40, 50, 160, 30);
        getContentPane().add(pass);
        pass.setBounds(40, 120, 160, 30);

        setSize(new java.awt.Dimension(254, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
            // TODO add your handling code here:
        BankOfficer a = BankOfficer.searchEmp(user.getText(), pass.getText());
        if(a != null){
            JOptionPane.showMessageDialog(this," "+a.getEmp_name()+"  log in sucess!");
            displayApp profile = new displayApp();
            profile.setVisible(true);
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Please try agian");
            setVisible(true);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/unlock.png")));
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/resource/locked.png")));
    }//GEN-LAST:event_loginButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField user;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
